### ISSUE TITLE
Some source files miss Apache license headers

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-runtime-docker#20]
Following [Apache license header guideline](http://www.apache.org/legal/src-headers.html), **all human-readable Apache-developed files that are included within a distribution must include the header text with few exceptions**. You can find few exceptions here: [which files do not require a license header](http://www.apache.org/legal/src-headers.html#faq-exceptions).

I used Apache Rat to check this repository after excluding a few files, and I got this report. We need to add Apache licensing header to those files.
```
Unapproved licenses:

  openwhisk-runtime-docker/core/actionProxy/Dockerfile
  openwhisk-runtime-docker/tests/dat/blackbox/badaction/Dockerfile
  openwhisk-runtime-docker/tests/dat/blackbox/badaction/README.md
  openwhisk-runtime-docker/tests/dat/blackbox/badproxy/Dockerfile
  openwhisk-runtime-docker/tests/dat/blackbox/badproxy/README.md
  openwhisk-runtime-docker/tests/src/test/resources/application.conf
  openwhisk-runtime-docker/ansible/environments/local/group_vars/all
  openwhisk-runtime-docker/ansible/environments/local/hosts
  openwhisk-runtime-docker/sdk/docker/Dockerfile
  openwhisk-runtime-docker/sdk/docker/example.c
```

The excluded files are:
```
**/*.json
**/**.gradle
**/gradlew
**/gradle/**
**/.**
**/templates/**
**/*.j2.*
**/.github/**
**/auth.whisk.system
**/auth.guest
**/i18n_resources.go
```

**Comment by csantanapr** [comment]
licenses has being added, I believe this issue is resolved now
