### ISSUE TITLE
add mode to disable re-init of an action

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-runtime-docker#48]
The Java proxy does not permit an action to be re-initialized [1]. This isn't true for the docker proxy or Python/Swift runtimes. All the runtimes should behave consistently. The basic action container tests suite will be extended to include a test for re-init, where the first init is expected to succeed but the second should fail. The action proxy will reject the request with status code 403 FORBIDDEN (although any non-20x is acceptable for rejection).

[1] https://github.com/apache/incubator-openwhisk-runtime-java/blob/3657b3889fd1ce03581184fcb07766a8c897a4d8/java8/proxy/src/main/java/openwhisk/java/action/Proxy.java#L72-L75

Making the fix at this level will address python and swift proxies as well.

**Comment by chetanmeh** [comment]
@rabbah May be create an issue in OpenWhisk Core repo and link runtime issues to that.
